### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by JRICKL** [nodfe/go_moso#1]
您好！我在使用过程中发现一些问题，来寻求您的帮助！
问题如下：
![5](https://user-images.githubusercontent.com/17766351/37027668-f94b6204-216c-11e8-98dc-47c17315f3f0.png)
然后我的网页如下
![4](https://user-images.githubusercontent.com/17766351/37027694-07727f70-216d-11e8-8219-3eafcb0f5e7b.png)
我分析是因为没有正确答案？这种情况该如何处理呢？

**Comment by nodfe** [comment]
Hi！你好！
当时写的时候答案是直接爬取正确答案页面的内容，所以如果正确答案页面如果没有答案的话是完成不了的。很抱歉！
