### ISSUE TITLE
都填对了，但是报错

### ISSUE THREAD

**Issue by 5m17h** [nodfe/go_moso#3]
![image](https://user-images.githubusercontent.com/31263162/55297121-3fbfd280-5455-11e9-812f-13c647636dd7.png)

**Comment by 5m17h** [comment]
登录是登录进去了，个人信息的参数都正确

**Comment by 5m17h** [comment]
然后运行到后面就报错，最终蓝墨云呈现的结果为：你已经用尽测试机会，但未成功提交答案。

**Comment by TongJiaqi0123** [comment]
我也是这个问题，楼主解决了么

**Comment by nodfe** [comment]
> 然后运行到后面就报错，最终蓝墨云呈现的结果为：你已经用尽测试机会，但未成功提交答案。

如果是这种情况的话是不适用于此脚本的，因为此脚本的工作方式为：先去提交一遍然后从答案页获取答案之后再去提交正确答案的，所以如果你的考试只有一次提交机会的话就不适用了
